version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: opensis_mysql
    restart: always
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opensis
      MYSQL_USER: opensis_user
      MYSQL_PASSWORD: opensis_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  opensis:
    build: .
    container_name: opensis_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: opensis_phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 100M

volumes:
  mysql_data:
